export const products = [
    { name: "Alpura clasica 200ml", price: 10 },
    { name: "Alpura clasica 1L", price: 28 },
    { name: "Alpura clasica 1.5L", price: 39 },
    { name: "Alpura semi 1L", price: 28 },
    { name: "Alpura light 1L", price: 28 },
    { name: "Alpura deslatosada 200ml", price: 10 },
    { name: "Alpura deslatosada 1L", price: 29 },
    { name: "Alpura deslatosada 1.5L", price: 40 },
    { name: "Alpura deslatosada light 1L", price: 29 },
    { name: "Alpura deslatosada light 1.5L", price: 40 },
    { name: "Alpura pasteurizada 1L", price: 27.5 },
    { name: "Alpura pasteurizada 1.89L", price: 46 },
    { name: "Alpura pasteurizada 3.78L", price: 90 },
    { name: "Vaquitas 200ml", price: 12 },
    { name: "Vaquitas 1L", price: 33 },
    { name: "Cafe lechero 315ml", price: 20 },
    { name: "Cafe lechero 1L", price: 35 },
    { name: "Selecta saborizada 315ml", price: 17 },
    { name: "Alpura pro deslactosada 1L", price: 36 },
    { name: "Alpura pro baja en grasa 1L", price: 36 },
    { name: "Selecta 1L", price: 29 },
    { name: "Selecta deslactosada", price: 30 },
    { name: "Lacdel 1L", price: 24 },
    { name: "Lacdel semi 1L", price: 24 },
    { name: "Lacdel deslactosada 1L", price: 24.5 },
    { name: "Crema alpura 200ml", price: 22 },
    { name: "Crema alpura 426ml", price: 43 },
    { name: "Crema alpura 900ml", price: 83 },
    { name: "Crema alpura 4L", price: 304 },
    { name: "Crema alpura deslactosada 200ml", price: 24 },
    { name: "Crema alpura deslactosada 426ml", price: 46 },
    { name: "Crema alpura deslactosada 900ml", price: 89 },
    { name: "Yoghurt alpura natural 125g", price: 7.5 },
    { name: "Yoghurt alpura natural 900g", price: 43.5 },
    { name: "Yoghurt alpura sabores 125g", price: 7.5 },
    { name: "Yoghurt alpura sabores 900g", price: 44 },
    { name: "Frutal 250ml", price: 13 },
    { name: "Frutal 1L", price: 33 },
    { name: "Yoghur alpura bebible 220g", price: 16 },
    { name: "Yoghur alpura bebible deslactosado 220g", price: 16.5 }
];
