export const products = [
    { name: "Arroz Basmati", price: 2.99 },
    { name: "Pasta Espagueti", price: 1.49 },
    { name: "Aceite de Oliva", price: 5.99 },
    { name: "Tomates Frescos", price: 3.49 },
    { name: "Leche Entera", price: 1.29 },
    { name: "Huevos Blancos", price: 2.49 },
    { name: "Pan Integral", price: 1.99 },
    { name: "Pollo Fresco", price: 4.99 },
    { name: "Pescado Salmón", price: 8.99 },
    { name: "Queso Cheddar", price: 3.79 },
    { name: "Yogurt Natural", price: 2.49 },
    { name: "Mantequilla", price: 2.19 },
    { name: "Jugo de Naranja", price: 3.99 },
    { name: "Manzanas", price: 2.99 },
    { name: "Plátanos", price: 1.49 },
    { name: "Lechuga", price: 1.99 },
    { name: "Papá", price: 1.29 },
    { name: "Cebolla", price: 1.59 },
    { name: "Ajo", price: 0.99 },
    { name: "Zanahorias", price: 1.49 },
    { name: "Pepino", price: 1.29 },
    { name: "Jitomate", price: 2.49 },
    { name: "Pechuga de Pollo", price: 6.99 },
    { name: "Salmón Congelado", price: 10.99 },
    { name: "Cereal de Maíz", price: 3.29 },
    { name: "Cereal de Avena", price: 2.49 },
    { name: "Galletas de Chocolate", price: 1.79 },
    { name: "Galletas de Vainilla", price: 1.49 },
    { name: "Papel Higiénico", price: 4.49 },
    { name: "Toallas de Papel", price: 3.29 },
    { name: "Detergente Líquido", price: 5.99 },
    { name: "Limón", price: 1.59 },
    { name: "Fresas", price: 3.49 },
    { name: "Uvas", price: 4.99 },
    { name: "Café Molido", price: 3.59 },
    { name: "Azúcar", price: 1.89 },
    { name: "Sal", price: 0.89 },
    { name: "Pimienta", price: 2.29 },
    { name: "Comino", price: 1.49 },
    { name: "Salsa de Soya", price: 1.69 },
    { name: "Vinagre", price: 1.29 },
    { name: "Mayonesa", price: 2.59 },
    { name: "Ketchup", price: 1.99 },
    { name: "Mostaza", price: 1.79 },
    { name: "Cereal de Trigo", price: 2.69 },
    { name: "Cereal Integral", price: 3.19 },
    { name: "Jugo de Manzana", price: 2.99 },
    { name: "Lentejas", price: 1.99 },
    { name: "Frijoles Negros", price: 2.19 },
    { name: "Papas Fritas", price: 2.49 },
    { name: "Galletas Saladas", price: 1.59 },
    { name: "Pechuga de Pavo", price: 5.99 },
    { name: "Bacon", price: 4.49 },
    { name: "Salmón Ahumado", price: 12.99 },
    { name: "Tortillas de Maíz", price: 1.49 },
    { name: "Tortillas de Harina", price: 1.79 },
    { name: "Aguacate", price: 2.99 },
    { name: "Mango", price: 3.49 },
    { name: "Piña", price: 3.99 },
    { name: "Melón", price: 4.49 },
    { name: "Cereal de Chocolate", price: 2.79 },
    { name: "Arándanos", price: 4.99 },
    { name: "Granola", price: 3.69 },
    { name: "Frutos Secos", price: 5.49 },
    { name: "Té Verde", price: 2.29 },
    { name: "Té Negro", price: 1.99 },
    { name: "Café Instantáneo", price: 3.99 },
    { name: "Café Espresso", price: 4.79 },
    { name: "Leche de Almendra", price: 2.69 },
    { name: "Leche de Coco", price: 3.29 },
    { name: "Leche de Soja", price: 2.99 },
    { name: "Sopa de Pollo", price: 3.49 },
    { name: "Sopa de Verduras", price: 2.89 },
    { name: "Sopa Instantánea", price: 1.29 },
    { name: "Fideos Instantáneos", price: 1.59 },
    { name: "Pechuga de Pollo Empanizada", price: 5.99 },
    { name: "Hamburguesas de Res", price: 7.99 },
    { name: "Hamburguesas de Pollo", price: 6.49 },
    { name: "Hot Dogs", price: 4.29 },
    { name: "Chorizo", price: 3.99 },
    { name: "Carne Molida", price: 6.29 },
    { name: "Costillas de Cerdo", price: 7.49 },
    { name: "Filete de Res", price: 9.99 },
    { name: "Pechuga de Pollo Congelada", price: 5.79 },
    { name: "Pescado Fileteado", price: 7.99 },
    { name: "Bistec de Res", price: 8.49 },
    { name: "Carne de Cerdo", price: 6.79 },
    { name: "Burgers de Vegetales", price: 5.49 },
    { name: "Fajitas de Pollo", price: 6.99 },
    { name: "Salmón Fresco", price: 11.99 },
    { name: "Camarones", price: 12.49 },
    { name: "Calamares", price: 10.29 },
    { name: "Manteca de Cerdo", price: 2.49 },
    { name: "Salsa Roja", price: 1.59 },
    { name: "Salsa Verde", price: 1.79 },
    { name: "Cilantro", price: 0.89 },
    { name: "Salsa BBQ", price: 2.69 },
    { name: "Aceite de Girasol", price: 3.19 },
    { name: "Aceite Vegetal", price: 1.99 },
    { name: "Mayonesa Ligera", price: 2.79 },
    { name: "Salsa de Tomate", price: 1.29 },
    { name: "Aceitunas", price: 3.59 },
    { name: "Chiles Jalapeños", price: 1.49 },
    { name: "Chiles Poblanos", price: 2.29 },
    { name: "Almejas", price: 9.99 },
    { name: "Mejillones", price: 8.49 },
    { name: "Pargo", price: 10.59 },
    { name: "Atún en Lata", price: 2.39 },
    { name: "Sardinas", price: 1.79 },
    { name: "Filetes de Pescado Congelado", price: 7.49 },
    { name: "Pan Baguette", price: 2.19 },
    { name: "Pan de Molde", price: 1.69 },
    { name: "Pan de Ajo", price: 2.29 },
    { name: "Galletas de Avena", price: 2.49 },
    { name: "Chocolates", price: 1.99 },
    { name: "Galletas Oreo", price: 2.99 },
    { name: "Caramelos", price: 1.49 },
    { name: "Chicles", price: 0.99 },
    { name: "Chocolatina", price: 1.29 },
    { name: "Helado de Vainilla", price: 4.99 },
    { name: "Helado de Fresa", price: 4.49 },
    { name: "Helado de Chocolate", price: 4.79 },
    { name: "Paletas", price: 2.49 },
    { name: "Papas Naturales", price: 2.19 },
    { name: "Papas de Limón", price: 2.39 },
    { name: "Chips de Queso", price: 2.29 },
    { name: "Agua Mineral", price: 1.49 },
    { name: "Agua con Gas", price: 1.79 },
    { name: "Refresco de Cola", price: 1.19 },
    { name: "Refresco de Naranja", price: 1.29 },
    { name: "Refresco de Limón", price: 1.19 },
    { name: "Jugo de Piña", price: 3.99 },
    { name: "Jugo de Uva", price: 3.79 },
    { name: "Jugo de Durazno", price: 3.49 },
    { name: "Jugo de Arándano", price: 4.49 },
    { name: "Jugo de Manzana Verde", price: 3.69 },
    { name: "Vino Tinto", price: 9.99 },
    { name: "Vino Blanco", price: 8.49 },
    { name: "Cerveza Rubia", price: 1.99 },
    { name: "Cerveza Oscura", price: 2.29 },
    { name: "Vino Rosado", price: 7.99 },
    { name: "Champagne", price: 12.99 },
    { name: "Tequila", price: 15.99 },
    { name: "Whisky", price: 19.99 },
    { name: "Ron Blanco", price: 12.49 },
    { name: "Vodka", price: 13.99 },
    { name: "Cerveza Artesanal", price: 2.99 },
    { name: "Aceite de Coco", price: 6.49 },
    { name: "Leche de Arroz", price: 2.39 },
    { name: "Sopa de Fideos", price: 1.69 },
    { name: "Galletas de Mantequilla", price: 2.99 },
    { name: "Mermelada de Fresa", price: 3.49 },
    { name: "Mermelada de Durazno", price: 3.69 },
    { name: "Mermelada de Mora", price: 3.29 },
    { name: "Jalea de Uva", price: 3.19 },
    { name: "Jalea de Naranja", price: 3.09 },
    { name: "Manteca de Cerdo", price: 2.29 },
    { name: "Aceitunas Verdes", price: 3.59 },
    { name: "Aceitunas Negras", price: 3.89 },
    { name: "Almendras", price: 4.99 },
    { name: "Nueces", price: 5.29 },
    { name: "Pistaches", price: 6.99 },
    { name: "Anacardos", price: 6.49 },
    { name: "Cacahuates", price: 2.59 },
    { name: "Girasoles", price: 2.49 },
    { name: "Salmón enlatado", price: 5.99 },
    { name: "Atún en Aceite", price: 2.99 },
    { name: "Frijoles Pintos", price: 1.79 },
    { name: "Lentejas Rojas", price: 2.59 },
    { name: "Arroz Integral", price: 3.29 },
    { name: "Arroz Blanco", price: 2.49 },
    { name: "Fideos de Arroz", price: 2.19 },
    { name: "Fideos de Sopa", price: 1.99 },
    { name: "Salsas de Tomate", price: 1.49 }
];
